### ISSUE TITLE
Unable to set WETH in test

### ISSUE THREAD

**Issue by devbest555** [enzymefinance/protocol#1048]
const denominationAsset = new WETH(config.weth, whales.weth);
I got error when I run it in the test.
Please help me ASAP.

**Comment by fubhy** [comment]
Hi. We've noticed that you've cloned (forked) our protocol repository, erased the entire git history, and have since removed our copyright and license statements. This is both in violation of the GPL License, under which this code was authored and published, as well as general open source spirit which we are committed to conserve. Please be advised that your behavior is not only incredibly unprofessional but also illegal. 

We cannot provide support for initiatives that violate these open source practices.

**Comment by devbest555** [comment]
> Hi. We've noticed that you've cloned (forked) our protocol repository, erased the entire git history, and have since removed our copyright and license statements. This is both in violation of the GPL License, under which this code was authored and published, as well as general open source spirit which we are committed to conserve. Please be advised that your behavior is not only incredibly unprofessional but also illegal.
> 
> We cannot provide support for initiatives that violate these open source practices.

hahaha. 
there are so many issues in your protocol.
I was trying to discover them.

**Comment by fubhy** [comment]
Cool. We are looking forward to your bug reports.
